# Short Numpy Tutorial

This is a very short introduction to the library numpy (http://www.numpy.org), focused on one of its basic data structures, `ndarray`. Numpy is the most important scientific package in the Python ecosystem, because it provides a common datastructure on which many other packages are build on.

![Python scientific ecosystem](http://luispedro.org/files/talks/2013/EuBIAS/figures/sciwheel.png)

To make this tutorial work on Python 3, let's import some future features:

In [1]:
from __future__ import print_function, division

In [2]:
# np is the standard abbreviation for numpy in the code
# Even the numpy docs use it
import numpy as np

## What is an ndarray?

The `ndarray` is the biggest contribution of numpy. An ndarray is

- a regular grid of N-dimensions,
- homogeneous by default (all the elements have the same type),
- contiguous block of memory with types corresponding to machine types (8-bit ints, 32 bit floats, 64-bit longs, ...).
- by default float64 is considered.

### Building an array (inline)

We can build an array explicitely from a Python list:

In [9]:
arr = np.array([
    [1.2, 2.3, 4.0],
    [1.2, 3.4, 5.2],
    [0.0, 1.0, 1.3],
    [0.0, 1.0, 2e-1]]) # Create a 2D array (4rijen, 3kolommen)

print(arr)
print(arr.shape)

[[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]]
(4, 3)


**Note:** 

Check what parameters the array() command has e.g. how to specify the type of the array. 

Create a 2D matrix of 3 rows and 4 columns initializing with values chosen by you and specify the type of the elements as float.

    

In [15]:
print (arr.dtype)

test_arr =  np.array([
    [1.2, 2.3, 4.0, 0.0],
    [1.2, 3.4, 5.2, 1.0],
    [0.0, 1.0, 1.3, 2e-1]], dtype = float) # Create a 2D array (3rijen, 4kolommen)

print(test_arr)
print(test_arr.dtype)
print(test_arr.shape)

float64
[[1.2 2.3 4.  0. ]
 [1.2 3.4 5.2 1. ]
 [0.  1.  1.3 0.2]]
float64
(3, 4)


**Exercise:** Check in [numpy](docs.scipy.org) what other ways there are to create an array?()

In [20]:
# With full() , creeer je een array met een specifieke waarde
arr = np.full((3, 3), 7)
print(arr)

# with empty() , creeer je een array met random waarden
arr = np.empty((2, 2))
print(arr)

# with zeros() , creeer je een array met nullen
arr = np.zeros((3, 3))
print(arr)

# with ones() , creeer je een array met enen
arr = np.ones((3, 3))
print(arr)

# with eye() , creeer je een array met enen op de diagonaal
arr = np.eye(3)
print(arr)

# with arange() , creeer je een array met een range van waarden
arr = np.arange(10)
print(arr)

# with linspace() , creeer je een array met een range van waarden
arr = np.linspace(0, 1, 10)
print(arr)

# with logspace() , creeer je een array met een range van waarden
arr = np.logspace(0, 3, 4)
print(arr)

# with random.rand() , creeer je een array met random waarden
arr = np.random.rand(3, 3)
print(arr)

# with random.randn() , creeer je een array met random waarden
arr = np.random.randn(3, 3)
print(arr)

# with random.randint() , creeer je een array met random waarden
arr = np.random.randint(0, 10, (3, 3))
print(arr)

# with random.seed() , creeer je een array met random waarden
np.random.seed(0)
arr = np.random.rand(3, 3)
print(arr)

# with random.seed() , creeer je een array met random waarden
np.random.seed(0)
arr = np.random.rand(3, 3)
print(arr)


[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.00000000e+000 9.56896609e-312]
 [0.00000000e+000 9.55959104e-312]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[   1.   10.  100. 1000.]
[[0.01463644 0.09343247 0.08892025]
 [0.37066368 0.13635191 0.38100558]
 [0.50983161 0.48673376 0.717471  ]]
[[-1.18283083 -1.21844817 -0.24673296]
 [-0.12446396  1.39017284  3.14480496]
 [-1.49126969 -0.55955251 -1.89474214]]
[[2 2 8]
 [1 6 3]
 [1 8 6]]
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


Create a three-dimensional array of 100x100x3 elements of type integer stored by 32 bits. How many ways to do it, do you find?

In [22]:
# Create a three-dimensional array of 100x100x3 elements of type integer stored by 32 bits. How many ways to do it, do you find?

# 1
arr = np.empty((100, 100, 3), dtype=np.int32)
print(arr)

# 2
arr = np.zeros((100, 100, 3), dtype=np.int32)
print(arr)

# 3
arr = np.full((100, 100, 3), 0, dtype=np.int32)
print(arr)

# 4
arr = np.random.randint(0, 10, (100, 100, 3), dtype=np.int32)
print(arr)

# 5
arr = np.random.rand(100, 100, 3)
print(arr)

# 6
arr = np.random.randn(100, 100, 3)
print(arr)

# 7
arr = np.random.randint(0, 10, (100, 100, 3))
print(arr)



[[[-331611824        450 -237150176]
  [       450 -249125249        450]
  [         0          0          0]
  ...
  [         0          0          0]
  [         0          0          0]
  [         0          0          0]]

 [[         0          0          0]
  [         0          0          0]
  [         0          0          0]
  ...
  [         0          0          0]
  [         0          0          0]
  [         0          0          0]]

 [[         0          0          0]
  [         0          0          0]
  [         0          0          0]
  ...
  [         0          0          0]
  [         0          0          0]
  [         0          0          0]]

 ...

 [[         0          0          0]
  [         0          0          0]
  [         0          0          0]
  ...
  [         0          0          0]
  [         0          0          0]
  [         0          0          0]]

 [[         0          0          0]
  [         0          0          0]


**Help**: [Array creation.](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html)

In [24]:
arr = np.array([
    [1.2, 2.3, 4.0],
    [1.2, 3.4, 5.2],
    [0.0, 1.0, 1.3],
    [0.0, 1.0, 2e-1]]) # Create a 2D array (4rijen, 3kolommen)

print(arr)
print(arr.shape)

[[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]]
(4, 3)


### Inspecting array properties

In [25]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

float64
2
(4, 3)


This array is of `float64`, it has 2 dimensions and its shape is 4 rows and 3 columns.

When constructing an array, we can explicitly specify the type:

In [27]:
iarr = np.array([1,2,3], dtype='uint8')
print(iarr)
print(iarr.dtype)

[1 2 3]
uint8


Arithmetic operations on the array : we should take into account that the type has to be respected.

In [28]:
arr *= 2.5
iarr *= 2
print(arr)
print(iarr)

[[ 3.    5.75 10.  ]
 [ 3.    8.5  13.  ]
 [ 0.    2.5   3.25]
 [ 0.    2.5   0.5 ]]
[2 4 6]


Ex: What is the problem of:

`iarr *= 2.5 ?`

In [ ]:
iarr *= 2.5 # Dit doet het niet omdat de array van het type uint8 is

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

The solution is to convert the array elements to float.

Check in [numpy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html) the different types and how to convert an array to a different type.

In [34]:
iarr.astype(float)*2.5

array([ 5., 10., 15.])

Has the type of the `iarr` array chaged?
Notice that numpy array creates variable with a certain type. If we do not consider it, our code will not work!

In [35]:
print(iarr.dtype)
print(iarr)


uint8
[2 4 6]


## Indexing

### Slicing & Dicing

We can use Python's `[]` operator to slice and address the array:

Below, you can see some examples of how we can read a matrix: 

In [36]:
print(arr) # The whole matrix
print(arr[0,0]) # 0 row, 0 column
print(arr[1]) # The whole 1 row
print(arr[:,2]) # The whole 2 column

[[ 3.    5.75 10.  ]
 [ 3.    8.5  13.  ]
 [ 0.    2.5   3.25]
 [ 0.    2.5   0.5 ]]
3.0
[ 3.   8.5 13. ]
[10.   13.    3.25  0.5 ]


### Working with slices of an array.

Slices share memory with the original array! In the following code, the variable `view` corresponds to a slice of the array `arr`.

In [46]:
# The position arr[1,0] = x. If we move its value to view, and modify view, we can see how arr[1,0] also is modifed.

print("Before: {}".format(arr[1,0]))

# adding 100
view = arr[1]
view[0] += 100

print("After: {}".format(arr[1,0]))

Before: 903.0
After: 1003.0
[1003.     8.5   13. ]


Note that by default Python assignation assumes sharing internal memory.

**Exercise:** How can we avoid memory sharing between variables? We should use the `.copy()` function.

In [51]:
print("Before: {}".format(arr[1,0])) # Orginele waarde van rij 1, kolom 0
view = arr.copy()[1] # Maaakt volledige kopie van de array arr, nieuwe kopie deelt geen geheugen met orginele array (wijzigingen in de kopie hebben geen invloed op de orginele array)
view[0] += 100
print("After: {}".format(arr[1,0]))
print("After view: {}".format(view[0]))


Before: 1003.0
After: 1003.0
After view: 1103.0


### Visual illustration of slicing

In [52]:
a = np.array([
       [ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

![slicing](https://scipy-lectures.github.io/_images/numpy_indexing.png)

This image is taken from [scipy-lectures](https://scipy-lectures.github.io/intro/numpy/array_object.html), a more complete tutorial on numpy than what we have here.

## [Boolean operations](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.logic.html)

An important subset of operations with numpy arrays concerns using logical operators to build boolean arrays. For example:


In [ ]:
print (arr)
is_greater_one = (arr >= 1.) # output= nieuwe array met True of False waarden (boolean)
print(is_greater_one)

[[  3.     5.75  10.  ]
 [103.     8.5   13.  ]
 [  0.     2.5    3.25]
 [  0.     2.5    0.5 ]]
[[ True  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True False]]


Put -100 in all elements of `arr` that are bigger than 10:

In [16]:
arr[(arr>10)] = -100
print(arr)

[[   3.      5.75   10.  ]
 [-100.      8.5  -100.  ]
 [   0.      2.5     3.25]
 [   0.      2.5     0.5 ]]


Construct a second array `arr2` that contains only the values of `arr` that are between 5 and 10:

In [17]:
arr2 = arr[(arr>5)&(arr<10)]
print(arr2)

[5.75 8.5 ]


Check what other [logical operations](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.logic.html) there are in numpy.

## [Basic functions on arrays](http://www.scipy-lectures.org/intro/numpy/operations.html)



In [18]:
arr.mean()

-13.666666666666666

Also available: `max`, `min`, `sum`, `ptp` (point-to-point, i.e., difference between maximum and minimum values).

These functions can also work *axis-wise*:

In [ ]:
arr.mean(axis=0) # Gemiddelde van de kolommen want axis=0 verwijst naar kolomen (verticaal) (axis=1 verwijst naar rijen)

array([-24.25  ,   4.8125, -21.5625])

In order to *save* code lines, an important trick is to combine logical operations:

In [54]:
is_greater_one = (arr > 1)
print(is_greater_one)
print(is_greater_one.mean())

[[ True  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True False]]
0.75


## Broadcasting

You can often perform operations along the array rows or columns: 

In [57]:
print(arr)
print("Now adding [1,1,0] to *every row*")
print()
arr += np.array([1,1,0])
print(arr)

[[5.000e+00 7.750e+00 1.000e+01]
 [1.005e+03 1.050e+01 1.300e+01]
 [2.000e+00 4.500e+00 3.250e+00]
 [2.000e+00 4.500e+00 5.000e-01]]
Now adding [1,1,0] to *every row*

[[6.000e+00 8.750e+00 1.000e+01]
 [1.006e+03 1.150e+01 1.300e+01]
 [3.000e+00 5.500e+00 3.250e+00]
 [3.000e+00 5.500e+00 5.000e-01]]


Add the vector [1,2,3,4] to each column:

In [61]:
print(arr)
arr3 = arr.transpose() # verwisselt assen van de arrau van (3,4) naar (4,3)
arr3 += np.array([1,2,3,4]) # kolom (verticaal) wordt toegevoegd aan elke rij (+) (dus eerste rij + 1, 2e rij +2 etc)
arr = arr3.transpose() # terug naar orginele array maar 
print(arr)

[[   9.     11.75   13.  ]
 [1012.     17.5    19.  ]
 [  12.     14.5    12.25]
 [  15.     17.5    12.5 ]]
[[  10.     12.75   14.  ]
 [1014.     19.5    21.  ]
 [  15.     17.5    15.25]
 [  19.     21.5    16.5 ]]


The exact [rules of how broadcasting works](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) are a bit complex to explain, but it generally works as expected. For example, if your data is a set of measurements for a sample, and your columns are the different types of measurements, then, you can easily remove the mean like this:

## Footnotes

[homogeneous]: There is a loophole to get heterogeneous arrays, namely an array of `object`. Then, you can store any Python object. This comes at the cost of decreased computational efficiency (both in terms of processing time and memory usage).

In [62]:
arr = np.array([
    [1.2, 2.3, 4.0],
    [1.2, 3.4, 5.2],
    [0.0, 1.0, 1.3],
    [0.0, 1.0, 2e-1]])
print ('The original matrix is:\n ', arr)
print()
print('The average value per column is: ',arr.mean(0))
print('The average value per row is: ',arr.mean(1))
print()
# here we make a copy of the variable arr since we will modify it several times
arr_aux1 = arr.copy()
arr_aux2 = arr.copy()

# we substract the average values to the whole matrix, first row based and later column based

arr_aux1 -= arr.mean(0)
print('The average value after subtracting the average values per row is: ') 
print(arr_aux1)

arr_aux2 = arr_aux2.transpose()
arr_aux2 -= arr.mean(1)
print('The average value after subtracting the average values per coloumn is: ')
print(arr_aux2)
print()

# The normalization is performed by dividing the matrix by its mean. 
print(arr.mean())
print ('The original matrix after normalizing is:\n ', arr/arr.mean())

The original matrix is:
  [[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]]

The average value per column is:  [0.6   1.925 2.675]
The average value per row is:  [2.5        3.26666667 0.76666667 0.4       ]

The average value after subtracting the average values per row is: 
[[ 0.6    0.375  1.325]
 [ 0.6    1.475  2.525]
 [-0.6   -0.925 -1.375]
 [-0.6   -0.925 -2.475]]
The average value after subtracting the average values per coloumn is: 
[[-1.3        -2.06666667 -0.76666667 -0.4       ]
 [-0.2         0.13333333  0.23333333  0.6       ]
 [ 1.5         1.93333333  0.53333333 -0.2       ]]

1.7333333333333332
The original matrix after normalizing is:
  [[0.69230769 1.32692308 2.30769231]
 [0.69230769 1.96153846 3.        ]
 [0.         0.57692308 0.75      ]
 [0.         0.57692308 0.11538462]]
